embedding_size: 64
feat_embed_dim: 64
weight_size: [64, 64]
learning_rate_scheduler: [0.96, 50]
lambda_coeff: 0.9
learning_rate: 0.001
n_mm_layers: 1
n_ui_layers: 2
knn_k: 10
mm_image_weight: 0.1
local_sample_p: 0.3
p_min: 0.1
p_max: 0.5
p_step: 0.02
eval_interval: 1


#baby
lambda_js: [0.1]
lambda_ui: [0.065]
lambda_ui_enhance: [0.03]
p_drop: 0.2
top_k: [5]
enable_residual: False

# #sports
#lambda_js: [0.1]
#lambda_ui: [0.065]
#lambda_ui_enhance: [0.2]
#p_drop: 0.4
#top_k: [10]
#enable_residual: True

# #clothing
#lambda_js: [0.05]
#lambda_ui: [0.065]
#lambda_ui_enhance: [0.5]
#p_drop: 0.5
#top_k: [10]
#enable_residual: True

hyper_parameters: ["lambda_js", "lambda_ui_enhance", "lambda_ui", "dropout","top_k"]